id: P010375
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18148
  title: མོ་ནད་གསོ་བ། བྱིས་པ་གསོ་བ། གདོན་ནད་གསོ་བ།
  author: ''
  volumes:
    b2323775b9bf43c8954ee4625b5f554b:
      image_group_id: I8LS18171
      title: ''
      volume_number: 1
      total_pages: 62
      base_file: v001.txt
