id: IA4344D97
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T17:59:33+00:00'
last_modified: '2022-06-08T13:08:22.062796+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18148
  title: མོ་ནད་གསོ་བ། བྱིས་པ་གསོ་བ། གདོན་ནད་གསོ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DF12:
      image_group_id: I8LS18171
      title: ''
      total_pages: 62
      order: 1
      base_file: DF12.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
